### ISSUE TITLE
Convert sphinx syntax to Markdown

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/pydoc-markdown#1]
It would be nice if Sphinx (reStructure Text) syntax could be converted sot that `:meth:`func_name``would be displayed as code. It must not necessarily link to the function, but it would be nice to have. Also, the`:param name: text...`and`:raise ExceptionName: text..` etc. should be handled.

Also, some use this kind of syntax:

```
Args:
    filename (str): The filename ...
Returns:
    str: The new filename ...
Raises:
    TypeError: Foo ...
```
