### ISSUE TITLE
mkdocs nav hierarchy support

### ISSUE THREAD

**Issue by cunningr** [NiklasRosenstein/pydoc-markdown#111]
I haven't been able to find a way to build a nav hierarchy for the generated mkdocs file.  Is this possible?  I am trying to blend authored project documentation with auto-generated doc-string docs.

E.g

```
nav:
    - Home: index.md
    - Git: a-quick-git-howto.md
    - Whats Cooking:
      - Entree:
        - Potato Soup: potato_soup.md
      - Mains:
        - Meat and Veg: meat_and_veg.md
      - Dessert:
        - Chocolate Mousse: chocolate_mouse.md
      - Tools:
        - Blender: blender.md
        - Knives: knives.md
```

**Comment by NiklasRosenstein** [comment]
Hey @cunningr ,

If you want to rely on Pydoc-Markdown generating the `mkdocs.yaml` configuration file for you, then you need to build the navigation entirely in the `$.renderer.pages` configuration.

```yaml
renderer:
  type: mkdocs
  pages:
    - title: Home
      name: index
      source: README.md
    - title: Getting Started
      source: docs/getting-started.md
    - title: API Documentation
      children:
        - title: Utils
          contents:
            - mylibrary.utils.*
        # ...
    mkdocs_config:
      # ... This will be rendered into `mkdocs.yaml`
      theme: alabaster
```

Otherwise you can just define the pages you want to automatically render with Pydoc-markdown and output them into the rest of your docs folder and then define your own `mkdocs.yaml` with your own nav (including the files that would be generated by Pydoc-markdown). (If you want to use that there's probably an option missing right now to avoid overwriting the `mkdocs.yaml` file from your docs directory).

```yaml
renderer:
  type: mkdocs
  pages:
    # ... Same page definition but you can skip the pages that use `source` to copy another file into the content directory
  output_directory: docs
  content_directory: .
```

Does that help you?
