### ISSUE TITLE
mkdocs: Copy media and extra.css files to build folder

### ISSUE THREAD

**Issue by cunningr** [NiklasRosenstein/pydoc-markdown#112]
currently I am using a small shell script to workaround this. E.g.

```
$ cat builddocs.sh
#!/bin/bash
pydoc-markdown docs/pydoc-markdown.yml
cp -r docs/media build/docs/docs/
cp docs/extra.css build/docs/docs/
mkdocs gh-deploy -f build/docs/mkdocs.yml
```

**Comment by NiklasRosenstein** [comment]
Hey @cunningr,

How about we add an option to specify actions to perform after rendering?

```yml
post_render:
  - action: rsync
    paths:
      - docs/media:build/docs/docs
      - docs/extra.css:build/docs/docs
```

(Note that I'm using `build/docs/content` because v3.0.3 will change the default docs dir from `build/docs/docs` to `build/docs/content`)
