### ISSUE TITLE
No errors, but also no content

### ISSUE THREAD

**Issue by StarfallProjects** [NiklasRosenstein/pydoc-markdown#127]
I'm running pydoc-markdown 3.1.1 with the following config:

```
loaders:
    - type: python
processors:
    - type: filter
    - type: smart
    - type: crossref
renderer:
    type: mkdocs
    site_name: Cape-Python-API
    content_directory_name: docs
    output_directory: ../pythonv1
    pages:
    - title: cape_privacy
      source: 'README.md'
    - title: cape_privacy.pandas
      contents:
      - cape_privacy.pandas._init_.py
      children:
      - title: pandas.registry
      contents:
      - cape_privacy.pandas.registry.py
```

There are no errors, and there is some output: I get all the files I'd expect:

![image](https://user-images.githubusercontent.com/10284570/86374767-d690c580-bc7c-11ea-8c4f-b1d19d33f4c9.png)

The README content is correctly picked up and copied over. When I run `mkdocs serve`, it displays. The other pages exist, and can be reached via the menu, but they are blank.

I'm not totally sure how much of the code would be picked up - it's possible `_init_.py` doesn't have the right contents. But `cape_privacy.pandas.registry.py` definitely contains docstrings that I would expect to see (and they appear fine with other tools such as pdoc)

The following is one part of the `registry.py` file:

```
def get(transformation: str) -> TransformationCtor:
    """Returns the constructor for the given key.

    Arguments:
        transformation: The key of transformation to retrieve.
    """
    return _registry.get(transformation, None)
```

Any idea why nothing is showing up?

**Comment by NiklasRosenstein** [comment]
Hey @StarfallProjects ! From a first look, I presume that it doesn't find any matching API objects for the `contents` that you specified. The strings in the `contents` list must be the FQNs of API objects, or a glob pattern matching on an FQN. An example from the config for Pydoc-Markdown itself:

https://github.com/NiklasRosenstein/pydoc-markdown/blob/5aa43d772a855b210bed95fc66a08f141dbcb9a6/pydoc-markdown.yaml#L38-L51

If you're on the latest Pydoc-Markdown version, you should see a log line if one of the elements in `contents` does not match an API object. Is that not the case?

https://github.com/NiklasRosenstein/pydoc-markdown/blob/5aa43d772a855b210bed95fc66a08f141dbcb9a6/src/pydoc_markdown/util/pages.py#L141-L148

Also note that the `filter` preprocessor removes any undocumented API objects from the tree by default.

https://github.com/NiklasRosenstein/pydoc-markdown/blob/5aa43d772a855b210bed95fc66a08f141dbcb9a6/src/pydoc_markdown/contrib/processors/filter.py#L49-L50

**Comment by StarfallProjects** [comment]
I don't get any errors or warnings at all.

I tried this:


```     
      - title: pandas.registry
      contents:
      - cape_privacy.pandas.registry.*
```

but pandas.registry.md is still empty.

registry.py has docstrings for both its functions.

**Comment by NiklasRosenstein** [comment]
Is there any chance you could share the source of your project? Or maybe make a small mocked version that reproduces the issue. Thanks

**Comment by StarfallProjects** [comment]
Thanks so much for your help!

This is the repo & branch: https://github.com/capeprivacy/documentation/tree/autogen

As you can see, I have an MkDocs site with various content, and a code repo, which I am trying to autogen and include in the full site.

The pydoc-markdown.yml isn't committed yet - I found it needed to be in with the code, which is in a submodule, so have added  it locally, and was gonna add it to the code repo once I was sure I was going with this approach (am trying out a few ways to autogen)

Here's the file contents:

```
loaders:
    - type: python
processors:
    - type: filter
    - type: smart
    - type: crossref
renderer:
    type: mkdocs
    site_name: Cape-Python-API
    content_directory_name: docs
    output_directory: ../pythonv1
    pages:
    - title: cape_privacy
      source: 'README.md'
    - title: cape_privacy.pandas
      contents:
      - cape_privacy.pandas._init_
      children:
      - title: pandas.registry
      contents:
      - cape_privacy.pandas.registry.*
```
