### ISSUE TITLE
Specify a source other than modules/packages

### ISSUE THREAD

**Issue by rraallvv** [NiklasRosenstein/pydoc-markdown#146]
Maybe I'm missing something but I couldn't find a way to specify a source directory for the package files other than `modules/packages`

**Comment by NiklasRosenstein** [comment]
@rraallvv Not 100% sure I can follow you there, since `modules` and `packages` are not used to specify a source directory, but rather the list of Python modules or packages (the latter is used to include all subpackages and -modules). You can specify the search path for the Python module(s) or package(s) using the `search_path` option.

https://pydoc-markdown.readthedocs.io/en/v3.3.0/docs/api-documentation/loaders/#search_path

```yaml
loaders:
- type: python
  search_path: [source/]
  packages: [mypackage]
```
