### ISSUE TITLE
escape_private doesn't work ?

### ISSUE THREAD

**Issue by ghost** [NiklasRosenstein/pydoc-markdown#159]
My `pydoc-markdown.yml` file : 
```yaml
loaders:
  - type: python
processors:
  - type: filter
    skip_empty_modules: true
    documented_only: false
    exclude_special: false
    exclude_private: false
renderer:
 - type:markdown
```
but the privates methods do not show up in the final markdown file (all other methods and functions print correctly). Is that normal ? 

The bash command : 
```bash
pydoc-markdown --py3 -m [my_module] -I ~/path/to/module/ > test.md
```
Version 3.5.0

**Comment by ghost** [comment]
Ok, I completely messed everything up. After scratching my head quite a while on the doc, pne cannot use options `-m`, `-I` or `-p` with a `pydoc-markdown.yml` configuration file.

Instead use 

```yaml
loaders:
  - type: python
    packages: [name_of_the_package1, name_of_the_package_2,] # in a list of strings
    search_path: [directory1, directory2, ..] # in a list of strings
processors:
  - type: filter
    skip_empty_modules: false
    exclude_private: false
    exclude_special: false
  - type: smart
  - type: crossref
renderer:
 - type:markdown
```
and then run 
```bash
pydoc-markdown > test.md
```
in the root directory of your package. I assume you followed [the official documentation on creating Python package](https://packaging.python.org/tutorials/packaging-projects/).

Hope this might help others !
