### ISSUE TITLE
Is there a way to modify the output such that functions do not show?

### ISSUE THREAD

**Issue by grantcurell** [NiklasRosenstein/pydoc-markdown#164]
Just out of curiosity, is there a way to make it so that functions in each file do not render?

Also - awesome project! Much appreciated!

**Comment by NiklasRosenstein** [comment]
Hey @grantcurell ,

I'm glad you like it. :) 

You can use a [`filter`](https://pydoc-markdown.readthedocs.io/en/v3.8.0/docs/api-documentation/processors/#filterprocessor-objects) processor and supply an expression that excludes API objects of type [`Function`](https://github.com/NiklasRosenstein/docspec/blob/69cc1d05c9eb43b4012ff57d959f197f8bb5a0ad/docspec/src/docspec/__init__.py#L94).

```yaml
processors:
- type: filter
  expression: default() and type(obj).__name__ != 'Function'
```

Lmk if that works for you.

Cheers,
