### ISSUE TITLE
How to force functions into TOC?

### ISSUE THREAD

**Issue by NoahCardoza** [NiklasRosenstein/pydoc-markdown#176]
I've been looking over the docs and I'm trying to get the table of contents to list functions, not just classes. Is this possible?

**Comment by NoahCardoza** [comment]
Writing this got e thinking and I noticed it wasn't based on the fact that it's a function, it was based on the title level. I as able to achive what I wanted by setting:

```yml
renderer:
    markdown:
        header_level_by_type:
           Function: 2
```

I hope this helps someone in the future!
