### ISSUE TITLE
[Feature] --bootstrap should detect existing poetry config

### ISSUE THREAD

**Issue by melMass** [NiklasRosenstein/pydoc-markdown#197]
Hi,

Sorry If I'm dumb, but I don't find the quickstart to give enough information, like from where are you supposed to issue the command, your python project root? I'm using poetry and running `pydoc-markdown --bootstrap mkdocs ` from the root returns `error: file already exists: 'pyproject.toml'`, will it create a subfolder, things like that. 
I'm pretty sure I will find the solution to all of this after playing with it a bit, but I guess I'm not the only one wondering those and it could be streamlined in the quickstart doc

Thanks for PyDoc ❤️ 

Close at will

**Comment by melMass** [comment]
I'm still struggling to understand how it works.
I created a `doc` folder in the root of my project, cd to it, and run
```shell
pydoc-markdown --bootstrap mkdocs -I .. 
> error: --bootstrap must be used as a sole argument
pydoc-markdown --bootstrap mkdocs
> created pydoc-markdown.yml
pydoc-markdown --server --open -I .. 
> error: renderer 'MarkdownRenderer' cannot be used with --server
```

**Comment by melMass** [comment]
Oh ok, it supports [reading configuration](https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/docs/configuration.md) from a `pyproject.toml` file (that's a great feature!)
Let me figure it out and summarize my ideas to make the quickstart/bootstrapping better.

**Comment by NiklasRosenstein** [comment]
Hey @melMass , sorry if the docs confused you. There's definitely room for improvement. 😄 

> ```
> pydoc-markdown --server --open -I .. 
> > error: renderer 'MarkdownRenderer' cannot be used with --server
> ```

Are you sure your `pydoc-markdown.yaml` had the original state after `pydoc-markdown --bootstrap mkdocs`? Because then that error is weird because it should be using the `MkDocsRenderer` which can be used with `--server`.

**Comment by melMass** [comment]
Ahah, yes, I know how some things can seem obvious from the inside sometimes, that's why I created the issue!

---

This is my layout:
```shell
|- myLib
  |- Documentation
    |- pydoc-markdown.yml 
  |- pyproject.toml
  |- moduleA
    |- ..
  |- moduleB
    |- ..
  |- setup.py
```

and `cat Documentation/pydoc-markdown.yml` returns:

```yaml
loaders:
  - type: python
processors:
  - type: filter
  - type: smart
  - type: crossref
renderer:
  type: mkdocs
  pages:
    - title: Home
      name: index
      source: README.md
    - title: API Documentation
      contents:
        - '*'
  mkdocs_config:
    mkdocs_config:
      site_name: My Project
      theme: readthedocs

```

All the commands I was referring to are issued from the `Documentation` folder (where the `pydoc-markdown.yaml` file reside)

**Comment by melMass** [comment]
Creating a `README.md` empty file in `Documentation` and running `pydoc-markdown --server --open` works:
![image](https://user-images.githubusercontent.com/7041726/128610808-dacd102e-d4ee-4b58-b3aa-31e328a1bee6.png)

But as soon as I add `-I ..` is fails with `error: renderer 'MarkdownRenderer' cannot be used with --server`

**Comment by NiklasRosenstein** [comment]
@melMass That is because if you use `-I,--search-path` it will not load the configuration file but instead fall back to using a default configuration that is aimed at producing Markdown content to stdout (hence the error about `MarkdownRenderer`). Though it would probably make sense to change the behavior here such that it always loads the config if it's present in the current directory.

https://github.com/NiklasRosenstein/pydoc-markdown/blob/924156a45975f138ca59442ca245c550becf371a/pydoc-markdown/src/pydoc_markdown/main.py#L295

You need to add the search path the your configuration like so:

```yml
loaders:
  - type: python
    search_path: [ .. ]
# ...
```
