### ISSUE TITLE
mkdocs: support extra_css & extra_javascript

### ISSUE THREAD

**Issue by casperdcl** [NiklasRosenstein/pydoc-markdown#215]
**Is your feature request related to a problem? Please describe.**

`mkdocs` supports extra config, e.g.:

```yml
mkdocs_config:
  extra_css: [somefile.css, somedir/another.css]
  extra_javascript: [js/more.js]
```

but `pydoc-markdown` doesn't copy those files over.

**Describe the solution you'd like**

Automatically pick up and copy these files.

Or at least document a work-around.

**Describe alternatives you've considered**

work-around:

```yml
hooks:
  post-render:
  - cp -r somefile.css somedir/ js/ build/docs/content/
```
