### ISSUE TITLE
Custom theme did not work

### ISSUE THREAD

**Issue by ghost** [NiklasRosenstein/pydoc-markdown#23]
Is it possible to use custom themes configured in pydocmd.yml?
I do not get this to run.

pydocmd.yml is in die project root.
custom_theme folder is also in the root.

```
site_name: "site name"

generate:
  - api/module.md:
    - package.module++

pages:
  - Home: index.md << docs/README.md
  - API:
    - Modules: api/module.md

docs_dir: docs
gens_dir: docs/_build/pydocmd
site_dir: docs/_build/site

theme: null
theme_dir: "custom_theme"
```

**Comment by NiklasRosenstein** [comment]
It would need to be a [MkDocs] theme. If MkDocs has a feature that you point it to some specific directory instead of to a theme name, then I don't know about it and I would probably need to add something that pydocmd supports it.

[MkDocs]: http://www.mkdocs.org/#theming-our-documentation

**Comment by NiklasRosenstein** [comment]
MkDocs supports an object for the `theme` property. See http://www.mkdocs.org/user-guide/configuration/#theme

Since the `theme` property in `pydocmd.yml` is copied to the `mkdocs.yml` configuration as-is, you can simply use the same type of object in your pydoc-markdown configuration.

```yaml
# pydocmd.yaml
theme:
  name: null
  custom_dir: mycustomtheme/
```

Let me know if it works for you.
