### ISSUE TITLE
Question: how do I replicate old pydoc-markdown setup with Novella?

### ISSUE THREAD

**Issue by mcarans** [NiklasRosenstein/pydoc-markdown#253]
It looks like you're making some major changes. How do I replicate my simple setup with the old pydoc-markdown of a main.md and the generated API documentation from the TOML description? (In readthedocs, it looks like [this](https://hdx-python-api.readthedocs.io/en/latest/).) Can I simply add tags at the bottom of main.md for the various API pages like "Configuration" that you can see below so that they appear under "API Documentation" in the menu on the left as now, or do I have to make one markdown page for each API page (I hope not as that would be a lot of tiny repetitive md files)? Where does the configuration go like loaders, renderer and source_linker or is that not needed any more?

My pyproject.toml looks like this:
```toml
[[tool.pydoc-markdown.loaders]]
type = "python"
search_path = ["src"]
packages = ["hdx.api", "hdx.data", "hdx.facades"]

[tool.pydoc-markdown.renderer]
type = "mkdocs"
output_directory = "docs/build"

    [tool.pydoc-markdown.renderer.mkdocs_config]
    site_name = "HDX Python API"
    theme = "readthedocs"
    repo_url = "https://github.com/OCHA-DAP/hdx-python-api"

    [tool.pydoc-markdown.renderer.markdown.source_linker]
    type = "github"
    repo = "OCHA-DAP/hdx-python-api"

    [[tool.pydoc-markdown.renderer.pages]]
    title = "Home"
    name = "index"
    source ="docs/main.md"

    [[tool.pydoc-markdown.renderer.pages]]
    title = "API Documentation"

        [[tool.pydoc-markdown.renderer.pages.children]]
        title = "Configuration"
        contents = ["hdx.api.configuration.*"]

        [[tool.pydoc-markdown.renderer.pages.children]]
        title = "Locations"
        contents = ["hdx.api.locations.*"]
...
```
