### ISSUE TITLE
Can't document constant values

### ISSUE THREAD

**Issue by benjamingorman** [NiklasRosenstein/pydoc-markdown#33]
pydocmd seems currently to lack support for documenting constant values.

As a test I added a new constant to `testmodule.__init__`:

```python
EXAMPLE_CONSTANT_VALUE = 42
```

I built docs for `testmodule` using the following yaml:

```yaml
site_name: testmodule Documentation
generate:
- main.md:
    - testmodule++
    - testmodule.EXAMPLE_CONSTANT_VALUE
pages:
- Home: main.md
```

The html renders like this:
![image](https://user-images.githubusercontent.com/6610341/36928546-9b646762-1e7e-11e8-8d54-af997a2e75f7.png)

So it seems to be using the docstring for Python's builtin `int` function.
