### ISSUE TITLE
Allow to filter children for `module+` synthax

### ISSUE THREAD

**Issue by Avsecz** [NiklasRosenstein/pydoc-markdown#54]
Thanks for a great package. It would be nice if one could exclude child elements by either listing them for each module specifically or by using a global exclude list:

```yaml
generate:
- baz/module.md:
  - foobar.more+:          # (+include members, but exclude some functions)
      exclude:
        - fn1
        - fn2
exclude:
  - get
```

Iw
