### ISSUE TITLE
Decoratored functions are not documented

### ISSUE THREAD

**Issue by aurelien-clu** [NiklasRosenstein/pydoc-markdown#74]
# Context

Functions having a decorator are not documented.

# Code

```python
def my_decorator(function):
    """
    :param function: function
    :return: function(self: Component, **kwargs)
    :raises: ValueError, something
    """
    def wrapper(self, *args, **kwargs):
        # check something and raise ValueError if condition is unmet
        return function(self, *args, **kwargs)
    return wrapper
```

```python
from decorator import my_decorator

class A:

    @my_decorator
    def some_function(self, something):
        """
        Some documentation

        :param something:
        :return:
        """
        pass
```

```yaml
[...]

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
  - yaml
  - python
  - bash
  - shell
  - sql

plugins:
  - search

loader:   pydocmd.loader.PythonLoader

preprocessor: pydocmd.restructuredtext.Preprocessor

headers: html
```

# Misc

I have not tried this minimal example but my code has this behavior in multiple file.

I have seen that https://github.com/NiklasRosenstein/pydoc-markdown/issues/65 fixed `@classmethod` but I guess it has not fixed it for other decorators?

Or could it be that `:raises: ValueError, something` is the problem?
