### ISSUE TITLE
pass config to mkdocs

### ISSUE THREAD

**Issue by casperdcl** [NiklasRosenstein/pydoc-markdown#88]
Would be nice if all unknown keys (https://www.mkdocs.org/user-guide/configuration/, e.g. `google_analytics`) are passed to `mkdocs.yml`. I think #27 was only fixed for CLI args.

**Comment by NiklasRosenstein** [comment]
In v3 the `MkdocsRenderer` has an `mkdocs_config` option. All keys in this config are forwarded to Mkdocs. Example:

```yml
renderer:
  type: mkdocs
  markdown:
    docstrings_as_blockquote: true
  mkdocs_config:
    theme: readthedocs
    # .. whatever else you need
```
